general:
    debug : False
    instance_name : "searx"
search:
    safe_search : 0
    autocomplete : "google"
    language : "en"
    ban_time_on_fail : 5
    max_ban_time_on_fail : 120
server:
    port : 8888
    bind_address : "127.0.0.1"
    secret_key : "3x+eYKQv2SCoyTnpHVHh6+hT+flEdGavN6p8GHkN4ubk"
    base_url : False
    image_proxy : False
    http_protocol_version : "1.1"
ui:
    static_path : ""
    templates_path : ""
    default_theme : oscar
    default_locale : "en"
    theme_args :
        oscar_style : logicodev
outgoing:
    request_timeout : 2.0
    useragent_suffix : ""
    pool_connections : 100
    pool_maxsize : 10
engines:
  - name: apk mirror
    engine: apkmirror
    timeout: 4.0
    shortcut: apkm
    disabled: True

  - name : arch linux wiki
    engine : archlinux
    shortcut : al
    disabled: True

  - name : archive is
    engine : xpath
    search_url : https://archive.is/{query}
    url_xpath : (//div[@class="TEXT-BLOCK"]/a)/@href
    title_xpath : (//div[@class="TEXT-BLOCK"]/a)
    content_xpath : //div[@class="TEXT-BLOCK"]/ul/li
    categories : general
    timeout : 7.0
    disabled : True
    shortcut : ai

  - name : arxiv
    engine : arxiv
    shortcut : arx
    categories : science
    timeout : 4.0
    disabled: True

  - name : base
    engine : base
    shortcut : bs

  - name : wikipedia
    engine : wikipedia
    shortcut : wp
    base_url : 'https://{language}.wikipedia.org/'

  - name : bing
    engine : bing
    shortcut : bi

  - name : bing images
    engine : bing_images
    shortcut : bii

  - name : bing news
    engine : bing_news
    shortcut : bin

  - name : bing videos
    engine : bing_videos
    shortcut : biv

  - name : bitbucket
    engine : xpath
    paging : True
    search_url : https://bitbucket.org/repo/all/{pageno}?name={query}
    url_xpath : //article[@class="repo-summary"]//a[@class="repo-link"]/@href
    title_xpath : //article[@class="repo-summary"]//a[@class="repo-link"]
    content_xpath : //article[@class="repo-summary"]/p
    categories : it
    timeout : 4.0
    disabled : True
    shortcut : bb

  - name : btdigg
    engine : btdigg
    shortcut : bt
    disabled: True

  - name : ccc-tv
    engine : xpath
    paging : False
    search_url : https://media.ccc.de/search/?q={query}
    url_xpath : //div[@class="caption"]/h3/a/@href
    title_xpath : //div[@class="caption"]/h3/a/text()
    content_xpath : //div[@class="caption"]/h4/@title
    categories : videos
    disabled : True
    shortcut : c3tv

  - name : crossref
    engine : json_engine
    paging : True
    search_url : https://search.crossref.org/dois?q={query}&page={pageno}
    url_query : doi
    title_query : title
    content_query : fullCitation
    categories : science
    shortcut : cr
    disabled: True

  - name : currency
    engine : currency_convert
    categories : general
    shortcut : cc
    disabled: True

  - name : deezer
    engine : deezer
    shortcut : dz
    disabled: True

  - name : deviantart
    engine : deviantart
    shortcut : da
    timeout: 3.0
    disabled: True

  - name : ddg definitions
    engine : duckduckgo_definitions
    shortcut : ddd
    weight : 2
    disabled : True

  - name : digbt
    engine : digbt
    shortcut : dbt
    timeout : 6.0
    disabled : True

  - name : digg
    engine : digg
    shortcut : dg
    disabled: True

  - name : erowid
    engine : xpath
    paging : True
    first_page_num : 0
    page_size : 30
    search_url : https://www.erowid.org/search.php?q={query}&s={pageno}
    url_xpath : //dl[@class="results-list"]/dt[@class="result-title"]/a/@href
    title_xpath : //dl[@class="results-list"]/dt[@class="result-title"]/a/text()
    content_xpath : //dl[@class="results-list"]/dd[@class="result-details"]
    categories : general
    shortcut : ew
    disabled : True

  - name : wikidata
    engine : wikidata
    shortcut : wd
    timeout : 3.0
    weight : 2

  - name : duckduckgo
    engine : duckduckgo
    shortcut : ddg
    disabled : True

  - name : duckduckgo images
    engine : duckduckgo_images
    shortcut : ddi
    timeout: 3.0
    disabled : True

  - name : etymonline
    engine : xpath
    paging : True
    search_url : https://etymonline.com/search?page={pageno}&q={query}
    url_xpath : //a[contains(@class, "word__name--")]/@href
    title_xpath : //a[contains(@class, "word__name--")]
    content_xpath : //section[contains(@class, "word__defination")]
    first_page_num : 1
    shortcut : et
    disabled : True

  - name : faroo
    engine : faroo
    shortcut : fa
    disabled : True

  - name : 1x
    engine : www1x
    shortcut : 1x
    disabled : True

  - name : fdroid
    engine : fdroid
    shortcut : fd
    disabled : True

  - name : flickr
    categories : images
    shortcut : fl
# You can use the engine using the official stable API, but you need an API key
# See : https://www.flickr.com/services/apps/create/
#    engine : flickr
#    api_key: 'apikey' # required!
# Or you can use the html non-stable engine, activated by default
    engine : flickr_noapi

  - name : free software directory
    engine : mediawiki
    shortcut : fsd
    categories : it
    base_url : https://directory.fsf.org/
    number_of_results : 5
    search_type : title
    timeout : 5.0
    disabled : True

  - name : frinkiac
    engine : frinkiac
    shortcut : frk
    disabled : True

  - name : genius
    engine : genius
    shortcut : gen
    disabled: True

  - name : gigablast
    engine : gigablast
    shortcut : gb
    timeout : 3.0
    disabled: True

  - name : gentoo
    engine : gentoo
    shortcut : ge
    disabled: True

  - name : gitlab
    engine : json_engine
    paging : True
    search_url : https://gitlab.com/api/v4/projects?search={query}&page={pageno}
    url_query : web_url
    title_query : name_with_namespace
    content_query : description
    page_size : 20
    categories : it
    shortcut : gl
    timeout : 10.0
    disabled : True

  - name : github
    engine : github
    shortcut : gh

  - name : google
    engine : google
    shortcut : go

  - name : google images
    engine : google_images
    shortcut : gi

  - name : google news
    engine : google_news
    shortcut : gn

  - name : google videos
    engine : google_videos
    shortcut : gv

  - name : google scholar
    engine : xpath
    paging : True
    search_url : https://scholar.google.com/scholar?start={pageno}&q={query}&hl=en&as_sdt=0,5&as_vis=1
    results_xpath : //div[contains(@class, "gs_r")]/div[@class="gs_ri"]
    url_xpath : .//h3/a/@href
    title_xpath : .//h3/a
    content_xpath : .//div[@class="gs_rs"]
    suggestion_xpath : //div[@id="gs_res_ccl_top"]//a/b
    page_size : 10
    first_page_num : 0
    categories : science
    shortcut : gos
    disabled: True

  - name : google play apps
    engine : xpath
    search_url : https://play.google.com/store/search?q={query}&c=apps
    results_xpath : '//div[@class="WHE7ib mpg5gc"]'
    title_xpath : './/div[@class="RZEgze"]//div[@title and not(@title="")]/a'
    url_xpath : './/div[@class="RZEgze"]//div[@title and not(@title="")]/a/@href'
    content_xpath : './/div[@class="RZEgze"]//a[@class="mnKHRc"]'
    thumbnail_xpath : './/div[@class="uzcko"]/div/span[1]//img/@data-src'
    categories : files
    shortcut : gpa
    disabled : True

  - name : google play movies
    engine : xpath
    search_url : https://play.google.com/store/search?q={query}&c=movies
    results_xpath : '//div[@class="WHE7ib mpg5gc"]'
    title_xpath : './/div[@class="RZEgze"]//div[@title and not(@title="")]/a'
    url_xpath : './/div[@class="RZEgze"]//div[@title and not(@title="")]/a/@href'
    content_xpath : './/div[@class="RZEgze"]//a[@class="mnKHRc"]'
    thumbnail_xpath : './/div[@class="uzcko"]/div/span[1]//img/@data-src'
    categories : videos
    shortcut : gpm
    disabled : True

  - name : google play music
    engine : xpath
    search_url : https://play.google.com/store/search?q={query}&c=music
    results_xpath : '//div[@class="WHE7ib mpg5gc"]'
    title_xpath : './/div[@class="RZEgze"]//div[@title and not(@title="")]/a'
    url_xpath : './/div[@class="RZEgze"]//div[@title and not(@title="")]/a/@href'
    content_xpath : './/div[@class="RZEgze"]//a[@class="mnKHRc"]'
    thumbnail_xpath : './/div[@class="uzcko"]/div/span[1]//img/@data-src'
    categories : music
    shortcut : gps
    disabled : True

  - name : geektimes
    engine : xpath
    paging : True
    search_url : https://geektimes.ru/search/page{pageno}/?q={query}
    url_xpath : //article[contains(@class, "post")]//a[@class="post__title_link"]/@href
    title_xpath : //article[contains(@class, "post")]//a[@class="post__title_link"]
    content_xpath : //article[contains(@class, "post")]//div[contains(@class, "post__text")]
    categories : it
    timeout : 4.0
    disabled : True
    shortcut : gt

  - name : habrahabr
    engine : xpath
    paging : True
    search_url : https://habrahabr.ru/search/page{pageno}/?q={query}
    url_xpath : //article[contains(@class, "post")]//a[@class="post__title_link"]/@href
    title_xpath : //article[contains(@class, "post")]//a[@class="post__title_link"]
    content_xpath : //article[contains(@class, "post")]//div[contains(@class, "post__text")]
    categories : it
    timeout : 4.0
    disabled : True
    shortcut : habr

  - name : hoogle
    engine : json_engine
    paging : True
    search_url : https://www.haskell.org/hoogle/?mode=json&hoogle={query}&start={pageno}
    results_query : results
    url_query : location
    title_query : self
    content_query : docs
    page_size : 20
    categories : it
    shortcut : ho
    disabled: True

  - name : ina
    engine : ina
    shortcut : in
    timeout : 6.0
    disabled : True

  - name : invidious
    engine : invidious
    base_url : 'https://invidio.us/'
    shortcut: iv
    timeout : 5.0
    disabled: True

  - name: kickass
    engine : kickass
    shortcut : kc
    timeout : 4.0
    disabled : True

  - name : library genesis
    engine : xpath
    search_url : http://libgen.io/search.php?req={query}
    url_xpath : //a[contains(@href,"bookfi.net")]/@href
    title_xpath : //a[contains(@href,"book/")]/text()[1]
    content_xpath : //td/a[1][contains(@href,"=author")]/text()
    categories : general
    timeout : 7.0
    disabled : True
    shortcut : lg

  - name : lobste.rs
    engine : xpath
    search_url : https://lobste.rs/search?utf8=%E2%9C%93&q={query}&what=stories&order=relevance
    results_xpath : //li[contains(@class, "story")]
    url_xpath : .//span[@class="link"]/a/@href
    title_xpath : .//span[@class="link"]/a
    content_xpath : .//a[@class="domain"]
    categories : it
    shortcut : lo
    disabled: True

  - name : microsoft academic
    engine : microsoft_academic
    categories : science
    shortcut : ma
    disabled: True

  - name : mixcloud
    engine : mixcloud
    shortcut : mc
    disabled: True

  - name : npm
    engine : json_engine
    paging : True
    search_url : https://api.npms.io/v2/search?q={query}&size=25&from={pageno}
    results_query : results
    url_query : package/links/npm
    title_query : package/name
    content_query : package/description
    page_size : 25
    categories : it
    disabled: True
    timeout: 5.0
    shortcut : npm

  - name : nyaa
    engine : nyaa
    shortcut : nt
    disabled : True

  - name : acgsou
    engine : acgsou
    shortcut : acg
    disabled : True
    timeout: 5.0

  - name : openairedatasets
    engine : json_engine
    paging : True
    search_url : http://api.openaire.eu/search/datasets?format=json&page={pageno}&size=10&title={query}
    results_query : response/results/result
    url_query : metadata/oaf:entity/oaf:result/children/instance/webresource/url/$
    title_query : metadata/oaf:entity/oaf:result/title/$
    content_query : metadata/oaf:entity/oaf:result/description/$
    categories : science
    shortcut : oad
    timeout: 5.0
    disabled: True

  - name : openairepublications
    engine : json_engine
    paging : True
    search_url : http://api.openaire.eu/search/publications?format=json&page={pageno}&size=10&title={query}
    results_query : response/results/result
    url_query : metadata/oaf:entity/oaf:result/children/instance/webresource/url/$
    title_query : metadata/oaf:entity/oaf:result/title/$
    content_query : metadata/oaf:entity/oaf:result/description/$
    categories : science
    shortcut : oap
    timeout: 5.0
    disabled: True

  - name : openstreetmap
    engine : openstreetmap
    shortcut : osm

  - name : openrepos
    engine : xpath
    paging : True
    search_url : https://openrepos.net/search/node/{query}?page={pageno}
    url_xpath : //li[@class="search-result"]//h3[@class="title"]/a/@href
    title_xpath : //li[@class="search-result"]//h3[@class="title"]/a
    content_xpath : //li[@class="search-result"]//div[@class="search-snippet-info"]//p[@class="search-snippet"]
    categories : files
    timeout : 4.0
    disabled : True
    shortcut : or

  - name : pdbe
    engine : pdbe
    shortcut : pdb
    disabled: True

  - name : photon
    engine : photon
    shortcut : ph
    disabled: True

  - name : piratebay
    engine : piratebay
    shortcut : tpb
    url: https://pirateproxy.red/
    timeout : 3.0
    disabled: True

  - name : pubmed
    engine : pubmed
    shortcut : pub
    categories: science
    timeout : 3.0
    disabled: True

  - name : qwant
    engine : qwant
    shortcut : qw
    categories : general
    disabled : True

  - name : qwant images
    engine : qwant
    shortcut : qwi
    categories : images

  - name : qwant news
    engine : qwant
    shortcut : qwn
    categories : news
    disabled: True

  - name : qwant social
    engine : qwant
    shortcut : qws
    categories : social media

  - name : reddit
    engine : reddit
    shortcut : re
    page_size : 25
    timeout : 10.0
    disabled : False

  - name : scanr structures
    shortcut: scs
    engine : scanr_structures
    disabled : True

  - name : soundcloud
    engine : soundcloud
    shortcut : sc
    disabled: True

  - name : stackoverflow
    engine : stackoverflow
    shortcut : st

  - name : searchcode doc
    engine : searchcode_doc
    shortcut : scd
    disabled: True

  - name : searchcode code
    engine : searchcode_code
    shortcut : scc
    disabled : True

  - name : framalibre
    engine : framalibre
    shortcut : frl
    disabled : True

#  - name : searx
#    engine : searx_engine
#    shortcut : se
#    instance_urls :
#        - http://127.0.0.1:8888/
#        - ...
#    disabled : True

  - name : semantic scholar
    engine : xpath
    paging : True
    search_url : https://www.semanticscholar.org/search?q={query}&sort=relevance&page={pageno}&ae=false
    results_xpath : //article
    url_xpath : .//div[@class="search-result-title"]/a/@href
    title_xpath : .//div[@class="search-result-title"]/a
    content_xpath : .//div[@class="search-result-abstract"]
    shortcut : se
    categories : science
    disabled: True

  - name : spotify
    engine : spotify
    shortcut : stf
    disabled: True

  - name : startpage
    engine : startpage
    shortcut : sp
    timeout : 6.0
    disabled : True

  - name : tokyotoshokan
    engine : tokyotoshokan
    shortcut : tt
    timeout : 6.0
    disabled : True

  - name : torrentz
    engine : torrentz
    shortcut : tor
    url: https://torrentz2.eu/
    timeout : 3.0
    disabled: True

  - name : twitter
    engine : twitter
    shortcut : tw

  - name : unsplash
    engine : unsplash
    disabled: True
    shortcut : us

  - name : yahoo
    engine : yahoo
    shortcut : yh
    disabled : True

  - name : yandex
    engine : yandex
    shortcut : yn
    disabled : True

  - name : yahoo news
    engine : yahoo_news
    shortcut : yhn
    disabled: True

  - name : youtube
    shortcut : yt
    # You can use the engine using the official stable API, but you need an API key
    # See : https://console.developers.google.com/project
    #    engine : youtube_api
    #    api_key: 'apikey' # required!
    # Or you can use the html non-stable engine, activated by default
    engine : youtube_noapi

  - name : dailymotion
    engine : dailymotion
    shortcut : dm
    disabled: True

  - name : vimeo
    engine : vimeo
    shortcut : vm
    disabled: True

  - name : wolframalpha
    shortcut : wa
    engine : wolframalpha_api
    api_key: '7UQ6JV-P447E5VPGH'
    ## engine : wolframalpha_noapi
    timeout: 6.0
    categories : science

  - name : dictzone
    engine : dictzone
    shortcut : dc
    disabled: True

  - name : mymemory translated
    engine : translated
    shortcut : tl
    timeout : 5.0
    disabled : True

  - name : voat
    engine: xpath
    shortcut: vo
    categories: social media
    search_url : https://searchvoat.co/?t={query}
    url_xpath : //div[@class="entry"]/p/a[contains(@class, "title")]/@href
    title_xpath : //div[@class="entry"]/p/a[contains(@class, "title")]
    content_xpath : //div[@class="entry"]/p/span[@class="domain"]/a/text()
    timeout : 10.0
    disabled : True

  - name : 1337x
    engine : 1337x
    shortcut : 1337x
    disabled : True

  - name : duden
    engine : duden
    shortcut : du
    disabled : True

  - name : seznam
    shortcut: szn
    engine: xpath
    paging : True
    search_url : https://search.seznam.cz/?q={query}&count=10&from={pageno}
    results_xpath: //div[@class="Page-content"]//div[contains(@class, "Result ")]
    url_xpath : ./h3/a/@href
    title_xpath : ./h3
    content_xpath : .//p[@class="Result-description"]
    suggestion_xpath: //div[@class="Related-container"]//div[@class="RelatedItem"]/div/span/a
    first_page_num : 0
    page_size : 10
    disabled : True

  - name : mojeek
    shortcut: mjk
    engine: xpath
    paging : True
    search_url : https://www.mojeek.com/search?q={query}&s={pageno}
    results_xpath: /html/body//div[@class="results"]/ul[@class="results-standard"]/li
    url_xpath : ./h2/a/@href
    title_xpath : ./h2
    content_xpath : ./p[@class="s"]
    suggestion_xpath : /html/body//div[@class="top-info"]/p[@class="top-info spell"]/a
    first_page_num : 1
    page_size : 10
    disabled : True

locales:
    en : English
    cs : Čeština (Czech)
    ja : 日本語 (Japanese)
    ru : Русский (Russian)
    sk : Slovenčina (Slovak)
    
doi_resolvers :
  oadoi.org : 'https://oadoi.org/'
  doi.org : 'https://doi.org/'
  doai.io  : 'http://doai.io/'
  sci-hub.tw : 'http://sci-hub.tw/'

default_doi_resolver : 'oadoi.org'